# INITIAL PARAMETERS
h = 11e3        # ALTITUDE
M0 = 0.85       # MACH
wT = 370e3      # TAKE OFF WEIGHT
wR = 0.8        # WEIGHT START TO END RATIO
wL = wR * wT    # LANDING WEIGHT
S = 285         # WING SURFACE AREA
bpr = 10        # BYPASS RATIO
yc = 1.4        # GAMMA COLD
yh = 1.333      # GAMMA HOT
to4 = 1560      # COMBUSTION TEMP
h_fuel = 43100  # FUEL ENERGY
pi_f = 1.5      # FAN RATIO
pi_c = 36       # COMBUSTOR RATIO
pi_b = 0.96     # BYPASS RATIO
n_i = 0.98      # INLET EFFICIENCY
n_if = 0.89     # FAN POLYTROPIC EFFICIENCY
n_ic = 0.90     # COMPRESSOR POLYTROPIC EFFICIENCY
n_b = 0.99      # COMBUSTOR EFFICIENCY
n_it = 0.90     # TURBINE POLYTROPIC EFFICIENCY
n_m = 0.99      # MECHANICAL EFFICIENCY
n_j = 0.99      # JET EFFICIENCY
cl = 0.4024     # LIFT COEFFICIENT

Pa = 0.22701    # AMBIENT PRESSURE IN BAR
Ta = 216.92     # AMBIENT TEMPERATURE IN K
R = 287         # GAS CONSTANT
cpa = 1.005     # AIR ENERGY CONSTANT
cpg = 1.148     # GAS ENERGY CONSTANT


# ITERATION PARAMETERS
bprMin = 5      # MINIMUM BYPASS PRESSURE RATIO FOR ITERATIVE DESIGN
bprMax = 20     # MAXIMUM BYPASS PRESSURE RATIO FOR ITERATIVE DESIGN

fprMin = 1.2    # MINIMUM FAN PRESSURE RATIO FOR ITERATIVE DESIGN
fprMax = 2.0    # MAXIMUM FAN PRESSURE RATIO FOR ITERATIVE DESIGN

cprMin = 20     # MINIMUM COMPRESSOR PRESSURE RATIO FOR ITERATIVE DESIGN
cprMax = 40     # MAXIMUM COMPRESSOR PRESSURE RATIO FOR ITERATIVE DESIGN
